

<h1>Delete Post</h1>
 <p>
Are you sure that you want to delete
     '<?php echo $this->escapeHtml($this->post->getTitle()); ?>' by
     '<?php echo $this->escapeHtml($this->post->getAuthor()); ?>'?
 </p>
 <form action="<?php echo $this->url('blog/delete', array(), true) ?>" method="post">
     <input type="submit" name="delete_confirmation" value="yes">
     <input type="submit" name="delete_confirmation" value="no">
 </form>